# Generated by Django 4.0.1 on 2022-03-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestFrameworkApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituciones',
            name='createdDate',
        ),
    ]
